# Generated by Django 4.0.3 on 2022-03-25 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('email', models.CharField(max_length=20, unique=True, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(default='12345678', max_length=20)),
                ('promotion', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(default='Inactive', max_length=20)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='editprofile.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('card_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('C', 'CREDIT'), ('D', 'DEBIT')], max_length=1)),
                ('billing_address', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.user')),
            ],
        ),
    ]
