# Generated by Django 4.0.3 on 2022-03-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
    ]
