# Generated by Django 4.0.3 on 2022-03-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
