# Generated by Django 4.0.3 on 2022-03-19 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0003_user_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20)),
                ('cardType', models.CharField(choices=[('C', 'CREDIT'), ('D', 'DEBIT')], max_length=1)),
                ('billingAddress', models.CharField(max_length=20)),
                ('expirationDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.user')),
            ],
        ),
    ]
