# Generated by Django 4.0.3 on 2022-03-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0004_paymentcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cardNumber',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
