# Generated by Django 4.0.3 on 2022-03-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0005_remove_paymentcard_id_alter_paymentcard_cardnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcard',
            old_name='billingAddress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='paymentcard',
            old_name='cardNumber',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='paymentcard',
            old_name='cardType',
            new_name='card_type',
        ),
        migrations.RenameField(
            model_name='paymentcard',
            old_name='expirationDate',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
