# Generated by Django 4.0.3 on 2022-03-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0006_rename_billingaddress_paymentcard_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='editprofile.usertype'),
        ),
    ]
