# Generated by Django 4.0.3 on 2022-03-20 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
