# Generated by Django 4.0.3 on 2022-03-28 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0009_alter_user_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
