# Generated by Django 4.0.3 on 2022-03-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0003_alter_user_password'),
        ('editprofile', '0010_alter_user_email'),
    ]

    operations = [
    ]
