# Generated by Django 4.0.3 on 2022-03-30 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0011_merge_0003_alter_user_password_0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
