# Generated by Django 4.0.3 on 2022-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
