# Generated by Django 4.0.3 on 2022-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0013_alter_paymentcard_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='last_digits',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
