# Generated by Django 4.0.3 on 2022-04-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0017_movie_genre_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('number_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editprofile.movie')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editprofile.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movieshow',
            constraint=models.UniqueConstraint(fields=('show_date', 'show_time'), name='unique_datetime'),
        ),
    ]
