# Generated by Django 4.0.3 on 2022-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0018_room_movieshow_movieshow_unique_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='show_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movieshow',
            name='show_time',
            field=models.CharField(max_length=255),
        ),
    ]
