# Generated by Django 4.0.3 on 2022-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0018_promotion'),
        ('editprofile', '0019_alter_movieshow_show_date_alter_movieshow_show_time'),
    ]

    operations = [
    ]
