# Generated by Django 4.0.3 on 2022-04-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0020_merge_20220418_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editprofile.paymentcard')),
                ('promoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editprofile.promotion')),
                ('showTimeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.movieshow')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.user')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.room')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('A', 'Adult'), ('C', 'Child'), ('S', 'Senior')], max_length=1)),
                ('ticket_price', models.CharField(max_length=10)),
                ('seatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.seat')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.movieshow')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.booking')),
                ('seatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.seat')),
                ('showTimeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editprofile.movieshow')),
            ],
        ),
    ]
