# Generated by Django 4.0.3 on 2022-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0021_booking_seat_ticket_reservedseat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('number', 'roomID'), name='unique_seat'),
        ),
    ]
