# Generated by Django 4.0.3 on 2022-04-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0022_seat_unique_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bookingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editprofile.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cardID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editprofile.paymentcard'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='promoID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editprofile.promotion'),
        ),
    ]
