# Generated by Django 4.0.3 on 2022-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0022_seat_unique_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshow',
            name='available_seats',
            field=models.IntegerField(default=40),
        ),
    ]
