# Generated by Django 4.0.3 on 2022-05-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0023_movieshow_available_seats'),
        ('editprofile', '0023_ticket_bookingid_alter_booking_cardid_and_more'),
    ]

    operations = [
    ]
