# Generated by Django 4.0.3 on 2022-05-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0025_paymentcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_expiry',
            field=models.DateField(),
        ),
    ]
