# Generated by Django 4.0.3 on 2022-05-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0023_movieshow_available_seats'),
        ('editprofile', '0026_alter_promotion_promotion_expiry'),
    ]

    operations = [
    ]
