# Generated by Django 4.0.3 on 2022-05-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0025_remove_booking_promoid'),
        ('editprofile', '0027_merge_20220505_2057'),
    ]

    operations = [
    ]
