# Generated by Django 4.0.3 on 2022-05-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0028_merge_20220505_2256'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservedseat',
            constraint=models.UniqueConstraint(fields=('seatID', 'showTimeID'), name='unique_reserved_seat'),
        ),
    ]
